## Settings for the micro:bit V2 example

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52833_xxAA --catch-reset --catch-hardfault --allow-erase-all"

rustflags = [
  "-C", "link-arg=-Tlink.x",
]
